services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    command: celery -A app.jobs.celery_app.celery_app worker --loglevel=INFO
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  streamlit:
    build: .
    command: streamlit run tools/streamlit_app.py --server.address 0.0.0.0 --server.port 8501
    environment:
      BACKEND_API_URL: http://api:8000/api/v1
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: busca_lead
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
